CREATE TABLE IF NOT EXISTS Client (
  id IDENTITY PRIMARY KEY,
  name VARCHAR(200) NOT NULL CHECK (LENGTH(name) >= 3 AND LENGTH(name) <= 200)
);

CREATE TABLE IF NOT EXISTS Planet (
  id VARCHAR PRIMARY KEY CHECK (id REGEXP '[A-Z0-9]+'),
  name VARCHAR(500) NOT NULL CHECK (LENGTH(name) >= 1 AND LENGTH(name) <= 500)
);

CREATE TABLE IF NOT EXISTS ticket (
id IDENTITY PRIMARY KEY,
created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
client_id BIGINT NOT NULL,
from_planet_id VARCHAR NOT NULL,
to_planet_id VARCHAR NOT NULL,
CONSTRAINT ticket_client FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE,
CONSTRAINT ticket_from_planet FOREIGN KEY (from_planet_id) REFERENCES planet (id) ON DELETE CASCADE,
CONSTRAINT ticket_to_planet FOREIGN KEY (to_planet_id) REFERENCES planet (id) ON DELETE CASCADE
);